<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Syrgas-MBP.lan" failures="0" tests="3" name="com.automation.test.CartPageTest" time="0.008" errors="1" timestamp="2023-01-21T02:32:05 CST" skipped="2">
  <testcase classname="com.automation.test.CartPageTest" name="verifyUserCanRemoveItemFromCart" time="0.008">
    <error message="Test Failed!" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Test Failed!
at com.automation.test.CartPageTest.verifyUserCanRemoveItemFromCart(CartPageTest.java:9)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- verifyUserCanRemoveItemFromCart -->
  <system-out/>
  <testcase classname="com.automation.test.CartPageTest" name="verifyUserCanAddItemIntoCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyUserCanAddItemIntoCart -->
  <system-out/>
  <testcase classname="com.automation.test.CartPageTest" name="verifyUserCanChangeQuantityOfItemOnCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyUserCanChangeQuantityOfItemOnCart -->
  <system-out/>
</testsuite> <!-- com.automation.test.CartPageTest -->
